apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: army
rules:
- apiGroups:
  - ""
  resourceNames:
  - apple-pod
  - prod-deploy
  - game-sts
  resources:
  - pods
  - secrets
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resourceNames:
  - apple-pod
  - prod-deploy
  - game-sts
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - create
  - delete
